apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: zippo
  name: zippo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zippo
  template:
    metadata:
      labels:
        app: zippo
    spec:
      containers:
      - image: ghcr.io/jan0ski/zippo:latest
        name: zippo
        args:
          - --address=0.0.0.0
          - --port=8080
          - --ssh-user=core
          - --ssh-pubkey=
          - --k8s=v1.20.0
          - --template=/etc/zippo/templates/zippo.tmpl
          - --config=/etc/zippo/config.yaml
        volumeMounts:
        - name: zippo-etc
          mountPath: /etc/zippo
        - name: zippo-etc-template
          mountPath: /etc/zippo/templates
      volumes:
      - name: zippo-etc
        emptyDir: {}
      - name: zippo-etc-template
        configMap:
          name: zippo-config
          items:
          - key: zippo.tmpl
            path: zippo.tmpl

  